services:

  abp_mvc:
    container_name: team3_mvc

    build:
      context: ../../
      dockerfile: src/Team3.Web.Mvc/Dockerfile

    env_file:
      - ../../.env

    environment:
      TZ: America/Toronto
      Kestrel__Endpoints__Http__Url: http://+:80

    ports:
      - "44312:80"

    volumes:
      - ../../Mvc-Logs:/app/App_Data/Logs

    restart: unless-stopped